-- Kapray Supabase regeneration schema backup
-- Generated on 2026-07-01 from the live app-facing Supabase tables.
--
-- Notes:
-- - This file recreates the public tables, app RPCs, triggers, indexes, grants,
--   and the vendor_review_summary view needed by the current app.
-- - Supabase storage bucket objects are not included. Media columns contain
--   storage paths only; back up bucket contents separately if needed.
-- - RLS policies could not be introspected with the app publishable key. Restore
--   policies from the Supabase dashboard/CLI if this is for production.

begin;

create extension if not exists pgcrypto;

drop view if exists public.vendor_review_summary;

drop trigger if exists trg_products_set_product_code on public.products;
drop trigger if exists trg_orders_set_order_no on public.orders;

drop function if exists public.set_products_product_code();
drop function if exists public.next_vendor_product_seq(bigint);
drop function if exists public.set_orders_order_no();
drop function if exists public.create_order_atomic_single_unit(
  bigint,
  uuid,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  jsonb,
  jsonb,
  jsonb,
  text,
  numeric,
  numeric,
  numeric,
  numeric,
  text,
  text,
  jsonb,
  text,
  text
);

drop table if exists public.vendor_reviews;
drop table if exists public.orders;
drop table if exists public.products;
drop table if exists public.vendor_product_counters;
drop table if exists public.vendor;
drop table if exists public.price_buckets;
drop table if exists public.price_bands;
drop table if exists public.wear_states;
drop table if exists public.work_densities;
drop table if exists public.work_types;
drop table if exists public.origin_cities;
drop table if exists public.fabric_types;
drop table if exists public.dress_types;

create table public.dress_types (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.fabric_types (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  image_path text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.origin_cities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table public.work_types (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table public.work_densities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table public.wear_states (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table public.price_bands (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  min_pkr numeric(12, 2),
  max_pkr numeric(12, 2),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.price_buckets (
  id bigint generated by default as identity primary key,
  label text not null,
  min_pkr numeric(12, 2) not null,
  max_pkr numeric(12, 2) not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vendor (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  location text,
  image text,
  email text,
  mobile text,
  landline text,
  shop_name text,
  address text,
  location_url text,
  status text,
  auth_user_id uuid,
  owner_user_id uuid,
  offers_dyeing boolean not null default false,
  offers_tailoring boolean not null default false,
  exports_enabled boolean not null default false,
  export_regions text[] not null default '{}'::text[],
  tailoring_options jsonb not null default '{}'::jsonb,
  profile_image_path text,
  banner_path text,
  certificate_paths text[],
  shop_image_paths text[],
  shop_video_paths text[]
);

create unique index vendor_auth_user_id_key
  on public.vendor (auth_user_id)
  where auth_user_id is not null;

create index vendor_owner_user_id_idx on public.vendor (owner_user_id);
create index vendor_status_idx on public.vendor (status);

create table public.vendor_product_counters (
  vendor_id bigint primary key references public.vendor(id) on delete cascade,
  last_seq integer not null default 0,
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  vendor_id bigint not null references public.vendor(id) on delete cascade,
  vendor_seq integer,
  product_code text,
  title text not null,
  inventory_qty numeric(12, 2) not null default 0,
  made_on_order boolean not null default false,
  product_category text not null default 'stitched_ready',
  spec jsonb not null default '{}'::jsonb,
  price jsonb not null default '{}'::jsonb,
  media jsonb not null default '{}'::jsonb
);

create unique index products_product_code_key
  on public.products (product_code)
  where product_code is not null;

create unique index products_vendor_seq_key
  on public.products (vendor_id, vendor_seq)
  where vendor_seq is not null;

create index products_vendor_id_idx on public.products (vendor_id);
create index products_product_category_idx on public.products (product_category);
create index products_created_at_idx on public.products (created_at desc);

create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  order_no text,
  status text not null default 'placed',
  vendor_id bigint not null references public.vendor(id) on delete restrict,
  product_id bigint not null references public.products(id) on delete restrict,
  buyer_auth_user_id uuid,
  buyer_name text not null,
  buyer_mobile text not null,
  buyer_email text,
  delivery_address text not null,
  city text not null,
  postal_code text,
  country text,
  destination_type text not null default 'inland',
  export_region text,
  notes text,
  product_code_snapshot text not null,
  title_snapshot text not null,
  spec_snapshot jsonb not null default '{}'::jsonb,
  price_snapshot jsonb not null default '{}'::jsonb,
  media_snapshot jsonb not null default '{}'::jsonb,
  currency text not null default 'PKR',
  subtotal_pkr numeric(12, 2),
  delivery_pkr numeric(12, 2),
  discount_pkr numeric(12, 2),
  total_pkr numeric(12, 2),
  size_mode text not null default 'standard',
  selected_size text,
  exact_measurements jsonb not null default '{}'::jsonb,
  payment_ref text,
  courier_name text,
  tracking_number text
);

create unique index orders_order_no_key
  on public.orders (order_no)
  where order_no is not null;

create index orders_vendor_id_idx on public.orders (vendor_id);
create index orders_product_id_idx on public.orders (product_id);
create index orders_buyer_mobile_idx on public.orders (buyer_mobile);
create index orders_status_idx on public.orders (status);
create index orders_created_at_idx on public.orders (created_at desc);

create table public.vendor_reviews (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  vendor_id bigint not null references public.vendor(id) on delete cascade,
  buyer_user_id uuid not null,
  order_id bigint not null references public.orders(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  vendor_reply text,
  vendor_reply_at timestamptz,
  is_verified_purchase boolean not null default false,
  is_public boolean not null default true,
  is_hidden boolean not null default false
);

create unique index vendor_reviews_order_buyer_key
  on public.vendor_reviews (order_id, buyer_user_id);

create index vendor_reviews_vendor_id_idx on public.vendor_reviews (vendor_id);
create index vendor_reviews_public_idx on public.vendor_reviews (vendor_id, is_public, is_hidden);

create or replace function public.next_vendor_product_seq(p_vendor_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_seq integer;
begin
  insert into public.vendor_product_counters as counters (
    vendor_id,
    last_seq,
    updated_at
  )
  values (
    p_vendor_id,
    1,
    now()
  )
  on conflict (vendor_id)
  do update set
    last_seq = counters.last_seq + 1,
    updated_at = now()
  returning last_seq into v_seq;

  return v_seq;
end;
$$;

create or replace function public.set_products_product_code()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.vendor_id is null then
    raise exception 'vendor_id is required';
  end if;

  if new.vendor_seq is null then
    new.vendor_seq := public.next_vendor_product_seq(new.vendor_id);
  end if;

  if nullif(btrim(coalesce(new.product_code, '')), '') is null then
    new.product_code := 'V' || new.vendor_id::text || '-P' || lpad(new.vendor_seq::text, 4, '0');
  end if;

  return new;
end;
$$;

create trigger trg_products_set_product_code
before insert on public.products
for each row
execute function public.set_products_product_code();

create or replace function public.set_orders_order_no()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if nullif(btrim(coalesce(new.order_no, '')), '') is null then
    new.order_no := 'ORD-' || to_char(coalesce(new.created_at, now()), 'YYYYMMDD') || '-' || lpad(new.id::text, 6, '0');
  end if;

  return new;
end;
$$;

create trigger trg_orders_set_order_no
before insert on public.orders
for each row
execute function public.set_orders_order_no();

create or replace function public.create_order_atomic_single_unit(
  p_product_id bigint,
  p_buyer_auth_user_id uuid,
  p_buyer_name text,
  p_buyer_mobile text,
  p_buyer_email text,
  p_delivery_address text,
  p_city text,
  p_notes text,
  p_product_code_snapshot text,
  p_title_snapshot text,
  p_spec_snapshot jsonb,
  p_price_snapshot jsonb,
  p_media_snapshot jsonb,
  p_currency text,
  p_subtotal_pkr numeric,
  p_delivery_pkr numeric,
  p_discount_pkr numeric,
  p_total_pkr numeric,
  p_size_mode text,
  p_selected_size text,
  p_exact_measurements jsonb,
  p_selected_variant_id text default null,
  p_selected_variant_size text default null
)
returns table (
  ok boolean,
  order_id bigint,
  message text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product record;
  v_order_id bigint;
  v_price jsonb;
  v_variants jsonb;
  v_new_variants jsonb := '[]'::jsonb;
  v_variant jsonb;
  v_new_variant jsonb;
  v_sizes jsonb;
  v_new_sizes jsonb;
  v_size_row jsonb;
  v_new_size_row jsonb;
  v_variant_matched boolean := false;
  v_size_matched boolean := false;
  v_current_qty integer := 0;
  v_product_category text;
  v_selected_variant_id text := nullif(btrim(coalesce(p_selected_variant_id, '')), '');
  v_selected_variant_size text := nullif(btrim(coalesce(p_selected_variant_size, '')), '');
  v_stock_deduction numeric := 1;
begin
  select
    id,
    vendor_id,
    coalesce(inventory_qty, 0) as inventory_qty,
    coalesce(made_on_order, false) as made_on_order,
    product_category,
    spec,
    price,
    media
  into v_product
  from public.products
  where id = p_product_id
  for update;

  if not found then
    return query select false, null::bigint, 'Product not found';
    return;
  end if;

  v_product_category := coalesce(v_product.product_category, '');

  if v_product.made_on_order = false then
    if v_product_category = 'stitched_ready'
       and v_selected_variant_id is not null
       and v_selected_variant_size is not null then

      v_price := coalesce(v_product.price, '{}'::jsonb);
      v_variants := coalesce(
        v_price -> 'variants',
        v_price -> 'ready_variants',
        v_price -> 'readyVariants',
        v_price -> 'stitched_variants',
        v_price -> 'stitchedVariants',
        '[]'::jsonb
      );

      if jsonb_typeof(v_variants) <> 'array' then
        return query select false, null::bigint, 'Variant inventory not found';
        return;
      end if;

      for v_variant in select value from jsonb_array_elements(v_variants) loop
        v_new_variant := v_variant;

        if coalesce(
          nullif(btrim(v_variant ->> 'id'), ''),
          nullif(btrim(v_variant ->> 'variant_id'), ''),
          nullif(btrim(v_variant ->> 'variantId'), ''),
          nullif(btrim(v_variant ->> 'label'), ''),
          nullif(btrim(v_variant ->> 'name'), '')
        ) = v_selected_variant_id then
          v_variant_matched := true;
          v_sizes := coalesce(v_variant -> 'sizes', '[]'::jsonb);

          if jsonb_typeof(v_sizes) <> 'array' then
            return query select false, null::bigint, 'Variant size inventory not found';
            return;
          end if;

          v_new_sizes := '[]'::jsonb;

          for v_size_row in select value from jsonb_array_elements(v_sizes) loop
            v_new_size_row := v_size_row;

            if lower(btrim(coalesce(
              v_size_row ->> 'size',
              v_size_row ->> 'label',
              v_size_row ->> 'name',
              v_size_row ->> 'value',
              ''
            ))) = lower(v_selected_variant_size) then
              v_size_matched := true;
              v_current_qty := greatest(0, coalesce(
                nullif(v_size_row ->> 'qty', '')::integer,
                nullif(v_size_row ->> 'stock_qty', '')::integer,
                nullif(v_size_row ->> 'stockQty', '')::integer,
                nullif(v_size_row ->> 'stock', '')::integer,
                nullif(v_size_row ->> 'quantity', '')::integer,
                0
              ));

              if v_current_qty < 1 then
                return query select false, null::bigint, 'Out of stock';
                return;
              end if;

              v_new_size_row := jsonb_set(v_new_size_row, '{qty}', to_jsonb(v_current_qty - 1), true);

              if v_new_size_row ? 'stock_qty' then
                v_new_size_row := jsonb_set(v_new_size_row, '{stock_qty}', to_jsonb(v_current_qty - 1), true);
              end if;

              if v_new_size_row ? 'stockQty' then
                v_new_size_row := jsonb_set(v_new_size_row, '{stockQty}', to_jsonb(v_current_qty - 1), true);
              end if;

              if v_new_size_row ? 'stock' then
                v_new_size_row := jsonb_set(v_new_size_row, '{stock}', to_jsonb(v_current_qty - 1), true);
              end if;

              if v_new_size_row ? 'quantity' then
                v_new_size_row := jsonb_set(v_new_size_row, '{quantity}', to_jsonb(v_current_qty - 1), true);
              end if;
            end if;

            v_new_sizes := v_new_sizes || jsonb_build_array(v_new_size_row);
          end loop;

          if not v_size_matched then
            return query select false, null::bigint, 'Selected size not found';
            return;
          end if;

          v_new_variant := jsonb_set(v_new_variant, '{sizes}', v_new_sizes, true);
        end if;

        v_new_variants := v_new_variants || jsonb_build_array(v_new_variant);
      end loop;

      if not v_variant_matched then
        return query select false, null::bigint, 'Selected variant not found';
        return;
      end if;

      if v_price ? 'variants' then
        v_price := jsonb_set(v_price, '{variants}', v_new_variants, true);
      elsif v_price ? 'ready_variants' then
        v_price := jsonb_set(v_price, '{ready_variants}', v_new_variants, true);
      elsif v_price ? 'readyVariants' then
        v_price := jsonb_set(v_price, '{readyVariants}', v_new_variants, true);
      elsif v_price ? 'stitched_variants' then
        v_price := jsonb_set(v_price, '{stitched_variants}', v_new_variants, true);
      elsif v_price ? 'stitchedVariants' then
        v_price := jsonb_set(v_price, '{stitchedVariants}', v_new_variants, true);
      else
        v_price := jsonb_set(v_price, '{variants}', v_new_variants, true);
      end if;

      update public.products
      set price = v_price
      where id = p_product_id;

    else
      if v_product_category in (
        'unstitched_plain',
        'unstitched_dyeing',
        'unstitched_dyeing_tailoring'
      ) then
        v_stock_deduction := greatest(
          0,
          coalesce(nullif(p_spec_snapshot ->> 'selected_fabric_length_m', '')::numeric, 0)
        );

        if v_stock_deduction <= 0 then
          return query select false, null::bigint, 'Fabric length is required';
          return;
        end if;
      else
        v_stock_deduction := 1;
      end if;

      if v_product.inventory_qty < v_stock_deduction then
        return query select false, null::bigint, 'Out of stock';
        return;
      end if;

      update public.products
      set inventory_qty = greatest(0, round(inventory_qty - v_stock_deduction, 2))
      where id = p_product_id;
    end if;
  end if;

  insert into public.orders (
    vendor_id,
    buyer_auth_user_id,
    buyer_name,
    buyer_mobile,
    buyer_email,
    delivery_address,
    city,
    notes,
    product_id,
    product_code_snapshot,
    title_snapshot,
    spec_snapshot,
    price_snapshot,
    media_snapshot,
    currency,
    subtotal_pkr,
    delivery_pkr,
    discount_pkr,
    total_pkr,
    size_mode,
    selected_size,
    exact_measurements,
    status
  )
  values (
    v_product.vendor_id,
    p_buyer_auth_user_id,
    p_buyer_name,
    p_buyer_mobile,
    p_buyer_email,
    p_delivery_address,
    p_city,
    p_notes,
    p_product_id,
    p_product_code_snapshot,
    p_title_snapshot,
    p_spec_snapshot,
    p_price_snapshot,
    p_media_snapshot,
    p_currency,
    p_subtotal_pkr,
    p_delivery_pkr,
    p_discount_pkr,
    p_total_pkr,
    p_size_mode,
    p_selected_size,
    p_exact_measurements,
    'placed'
  )
  returning id into v_order_id;

  return query select true, v_order_id, 'Order created';
end;
$$;

create or replace view public.vendor_review_summary as
select
  vendor_id,
  round(avg(rating)::numeric, 2) as average_rating,
  count(*)::bigint as review_count,
  count(*) filter (where rating = 5)::bigint as rating_5_count,
  count(*) filter (where rating = 4)::bigint as rating_4_count,
  count(*) filter (where rating = 3)::bigint as rating_3_count,
  count(*) filter (where rating = 2)::bigint as rating_2_count,
  count(*) filter (where rating = 1)::bigint as rating_1_count
from public.vendor_reviews
where is_public = true
  and is_hidden = false
group by vendor_id;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'grant usage on schema public to anon';
    execute 'grant select, insert, update, delete on all tables in schema public to anon';
    execute 'grant usage, select on all sequences in schema public to anon';
    execute 'grant execute on all functions in schema public to anon';
  end if;

  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'grant usage on schema public to authenticated';
    execute 'grant select, insert, update, delete on all tables in schema public to authenticated';
    execute 'grant usage, select on all sequences in schema public to authenticated';
    execute 'grant execute on all functions in schema public to authenticated';
  end if;

  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant usage on schema public to service_role';
    execute 'grant all privileges on all tables in schema public to service_role';
    execute 'grant all privileges on all sequences in schema public to service_role';
    execute 'grant execute on all functions in schema public to service_role';
  end if;
end;
$$;

commit;
