import { StyleSheet } from "react-native";
import { BUYER_COLORS as colors } from "@/constants/buyer";

export const buyerReviewStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: {
    padding: 16,
    paddingBottom: 24,
    backgroundColor: colors.background,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  closeBtn: {
    minHeight: 40,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: colors.blueSoft,
    borderWidth: 1,
    borderColor: colors.blueBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  closeBtnText: { color: colors.blue, fontSize: 14, fontWeight: "700" },
  title: { fontSize: 18, fontWeight: "700", color: colors.text },
  card: {
    marginTop: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: 18,
  },
  meta: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.muted,
    fontWeight: "500",
  },
  label: { marginTop: 16, fontSize: 14, fontWeight: "700", color: colors.text },
  starPickerWrap: { marginTop: 6 },
  starRow: { marginTop: 10, flexDirection: "row", gap: 10 },
  starBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.blueBorder,
    backgroundColor: colors.blueSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  starBtnOn: { backgroundColor: colors.blue, borderColor: colors.blue },
  starBtnText: { fontSize: 22, fontWeight: "700", color: colors.blue },
  starBtnTextOn: { color: colors.card },
  previewRow: { marginTop: 12 },
  input: {
    marginTop: 10,
    minHeight: 120,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.card,
  },
  submitBtn: {
    marginTop: 18,
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: colors.blue,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  submitBtnText: { color: colors.card, fontSize: 14, fontWeight: "700" },
  disabledBtn: { opacity: 0.6 },
  pressed: { opacity: 0.82 },
});
