import { StyleSheet } from "react-native";
import {
  BUYER_COLORS as colors,
  BUYER_PROFILE_SCREEN_WIDTH as width,
} from "@/constants/buyer";

export const buyerProfileStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: {
    padding: 16,
    paddingBottom: 24,
    backgroundColor: colors.background,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  title: { fontSize: 18, fontWeight: "700", color: colors.text },
  section: {
    marginTop: 18,
    fontSize: 15,
    fontWeight: "700",
    color: colors.text,
  },
  linkBtn: {
    minHeight: 40,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: colors.blueSoft,
    borderWidth: 1,
    borderColor: colors.blueBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  linkBtnInline: {
    marginTop: 10,
    alignSelf: "flex-start",
    minHeight: 40,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: colors.blueSoft,
    borderWidth: 1,
    borderColor: colors.blueBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  linkText: { color: colors.blue, fontSize: 14, fontWeight: "700" },
  loadingRow: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  loadingText: { fontSize: 13, color: colors.muted, fontWeight: "600" },
  card: {
    marginTop: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: 18,
  },
  metaCard: { paddingVertical: 12 },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 2,
  },
  meta: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    color: colors.muted,
    fontWeight: "500",
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 6,
  },
  metaRowSpaced: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  row: { marginTop: 10 },
  label: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: 0.2,
  },
  value: {
    marginTop: 4,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    color: colors.text,
  },
  mediaBlock: {
    marginTop: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    overflow: "hidden",
  },
  heroWrap: { width: "100%", backgroundColor: colors.card },
  heroImage: {
    width: "100%",
    height: 230,
    resizeMode: "cover",
    backgroundColor: colors.mediaPlaceholder,
  },
  profileRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatarWrap: {
    width: 74,
    height: 74,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
  },
  avatarPress: { width: "100%", height: "100%" },
  avatarImg: { width: "100%", height: "100%", resizeMode: "cover" },
  avatarFallback: {
    width: "100%",
    height: "100%",
    backgroundColor: colors.blue,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarFallbackText: { fontSize: 28, fontWeight: "700", color: colors.card },
  headerInfo: { flex: 1 },
  nameText: { fontSize: 16, fontWeight: "700", color: colors.text },
  shopText: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: "500",
    color: colors.muted,
  },
  statusText: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    color: colors.muted,
  },
  thumbRow: { flexDirection: "row", gap: 10, paddingTop: 10, paddingBottom: 4 },
  thumbWrap: {
    width: 84,
    height: 84,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
  },
  thumb: {
    width: "100%",
    height: "100%",
    backgroundColor: colors.mediaPlaceholder,
  },
  empty: {
    marginTop: 10,
    fontSize: 13,
    color: colors.muted,
    fontWeight: "500",
  },
  videoBox: {
    marginTop: 10,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
  },
  video: { width: "100%", height: 220 },
  videoThumb: {
    width: 110,
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    alignItems: "center",
    justifyContent: "center",
  },
  videoThumbOn: {
    borderColor: colors.blue,
    borderWidth: 2,
    backgroundColor: colors.blueSoft,
  },
  videoThumbText: { color: colors.blue, fontWeight: "700", fontSize: 12 },
  pressed: { opacity: 0.82 },
  viewerContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.95)",
    justifyContent: "center",
  },
  viewerSlide: {
    width,
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  viewerImage: { width, height: "100%", resizeMode: "contain" },
  closeButton: {
    position: "absolute",
    top: 40,
    right: 18,
    width: 44,
    height: 44,
    borderRadius: 999,
    backgroundColor: colors.overlay,
    alignItems: "center",
    justifyContent: "center",
  },
  closeText: { color: colors.card, fontSize: 20, fontWeight: "900" },
  indexCaption: {
    position: "absolute",
    bottom: 34,
    alignSelf: "center",
    backgroundColor: colors.overlay,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  indexText: { color: colors.card, fontWeight: "900", fontSize: 14 },
});
