create table if not exists public.storage_delete_queue (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  bucket_id text not null,
  object_path text not null,
  source_table text not null default 'unknown',
  source_id bigint,
  source_key text,
  attempts integer not null default 0,
  locked_at timestamptz,
  locked_by text,
  processed_at timestamptz,
  last_error text,
  constraint storage_delete_queue_path_not_blank check (
    btrim(bucket_id) <> '' and btrim(object_path) <> ''
  ),
  constraint storage_delete_queue_attempts_nonnegative check (attempts >= 0)
);

alter table public.storage_delete_queue
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists bucket_id text,
  add column if not exists object_path text,
  add column if not exists source_table text not null default 'unknown',
  add column if not exists source_id bigint,
  add column if not exists source_key text,
  add column if not exists attempts integer not null default 0,
  add column if not exists locked_at timestamptz,
  add column if not exists locked_by text,
  add column if not exists processed_at timestamptz,
  add column if not exists last_error text;

update public.storage_delete_queue
set source_table = 'unknown'
where nullif(btrim(coalesce(source_table, '')), '') is null;

update public.storage_delete_queue
set attempts = 0
where attempts is null or attempts < 0;

alter table public.storage_delete_queue
  alter column bucket_id set not null,
  alter column object_path set not null,
  alter column source_table set not null,
  alter column attempts set not null;

do $$
begin
  alter table public.storage_delete_queue
    add constraint storage_delete_queue_path_not_blank check (
      btrim(bucket_id) <> '' and btrim(object_path) <> ''
    );
exception
  when duplicate_object then
    null;
end $$;

do $$
begin
  alter table public.storage_delete_queue
    add constraint storage_delete_queue_attempts_nonnegative check (attempts >= 0);
exception
  when duplicate_object then
    null;
end $$;

create unique index if not exists storage_delete_queue_bucket_path_key
  on public.storage_delete_queue (bucket_id, object_path);

create index if not exists storage_delete_queue_pending_idx
  on public.storage_delete_queue (id)
  where processed_at is null;

create index if not exists storage_delete_queue_source_idx
  on public.storage_delete_queue (source_table, source_id);

alter table public.storage_delete_queue enable row level security;

revoke all on table public.storage_delete_queue from anon, authenticated;
grant select, insert, update, delete on table public.storage_delete_queue to service_role;

do $$
begin
  grant usage, select on sequence public.storage_delete_queue_id_seq to service_role;
exception
  when undefined_object then
    null;
end $$;

create or replace function public.set_storage_delete_queue_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_storage_delete_queue_updated_at
on public.storage_delete_queue;

create trigger trg_storage_delete_queue_updated_at
before update on public.storage_delete_queue
for each row
execute function public.set_storage_delete_queue_updated_at();

create or replace function public.enqueue_storage_delete(
  p_bucket_id text,
  p_object_path text,
  p_source_table text default 'unknown',
  p_source_id bigint default null,
  p_source_key text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if nullif(btrim(coalesce(p_bucket_id, '')), '') is null then
    return;
  end if;

  if nullif(btrim(coalesce(p_object_path, '')), '') is null then
    return;
  end if;

  insert into public.storage_delete_queue (
    bucket_id,
    object_path,
    source_table,
    source_id,
    source_key
  )
  values (
    btrim(p_bucket_id),
    btrim(p_object_path),
    coalesce(nullif(btrim(coalesce(p_source_table, '')), ''), 'unknown'),
    p_source_id,
    nullif(btrim(coalesce(p_source_key, '')), '')
  )
  on conflict (bucket_id, object_path)
  do update set
    updated_at = now(),
    source_table = case
      when public.storage_delete_queue.processed_at is null
        then public.storage_delete_queue.source_table
      else excluded.source_table
    end,
    source_id = case
      when public.storage_delete_queue.processed_at is null
        then public.storage_delete_queue.source_id
      else excluded.source_id
    end,
    source_key = case
      when public.storage_delete_queue.processed_at is null
        then public.storage_delete_queue.source_key
      else excluded.source_key
    end,
    attempts = case
      when public.storage_delete_queue.processed_at is null
        then public.storage_delete_queue.attempts
      else 0
    end,
    locked_at = null,
    locked_by = null,
    processed_at = null,
    last_error = null;
end;
$$;

revoke all on function public.enqueue_storage_delete(text, text, text, bigint, text)
from public;

create or replace function public.enqueue_storage_delete_prefix(
  p_bucket_id text,
  p_prefix text,
  p_source_table text default 'unknown',
  p_source_id bigint default null,
  p_source_key text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer := 0;
begin
  if nullif(btrim(coalesce(p_bucket_id, '')), '') is null then
    return 0;
  end if;

  if nullif(btrim(coalesce(p_prefix, '')), '') is null then
    return 0;
  end if;

  insert into public.storage_delete_queue (
    bucket_id,
    object_path,
    source_table,
    source_id,
    source_key
  )
  select
    storage_object.bucket_id,
    storage_object.name,
    coalesce(nullif(btrim(coalesce(p_source_table, '')), ''), 'unknown'),
    p_source_id,
    nullif(btrim(coalesce(p_source_key, '')), '')
  from storage.objects as storage_object
  where storage_object.bucket_id = btrim(p_bucket_id)
    and storage_object.name like btrim(p_prefix) || '%'
  on conflict (bucket_id, object_path)
  do update set
    updated_at = now(),
    source_table = case
      when public.storage_delete_queue.processed_at is null
        then public.storage_delete_queue.source_table
      else excluded.source_table
    end,
    source_id = case
      when public.storage_delete_queue.processed_at is null
        then public.storage_delete_queue.source_id
      else excluded.source_id
    end,
    source_key = case
      when public.storage_delete_queue.processed_at is null
        then public.storage_delete_queue.source_key
      else excluded.source_key
    end,
    attempts = case
      when public.storage_delete_queue.processed_at is null
        then public.storage_delete_queue.attempts
      else 0
    end,
    locked_at = null,
    locked_by = null,
    processed_at = null,
    last_error = null;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.enqueue_storage_delete_prefix(text, text, text, bigint, text)
from public;

create or replace function public.queue_deleted_product_storage()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product_code text;
  v_prefix text;
begin
  v_product_code := nullif(btrim(coalesce(old.product_code, '')), '');

  if old.vendor_id is null or v_product_code is null then
    return old;
  end if;

  v_prefix := 'vendors/' || old.vendor_id::text || '/products/' ||
    v_product_code || '/';

  perform public.enqueue_storage_delete_prefix(
    'vendor_images',
    v_prefix,
    'products',
    old.id,
    v_product_code
  );

  return old;
end;
$$;

drop trigger if exists trg_products_queue_storage_delete
on public.products;

create trigger trg_products_queue_storage_delete
after delete on public.products
for each row
execute function public.queue_deleted_product_storage();

create or replace function public.queue_deleted_vendor_storage()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prefix text;
begin
  if old.id is null then
    return old;
  end if;

  v_prefix := 'vendors/' || old.id::text || '/';

  perform public.enqueue_storage_delete_prefix(
    'vendor_images',
    v_prefix,
    'vendor',
    old.id,
    old.id::text
  );

  return old;
end;
$$;

drop trigger if exists trg_vendor_queue_storage_delete
on public.vendor;

create trigger trg_vendor_queue_storage_delete
after delete on public.vendor
for each row
execute function public.queue_deleted_vendor_storage();
